language: ruby
before_install:
  # jruby-head does not have bundler.
  - which bundle || gem install bundler
rvm:
    #- 1.8.7 #no longer supported as min requirements are 1.9.3
    #- 1.9.2 #no longer supported as min requirements are 1.9.3
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.1
  - ruby-head
    #- jruby-18mode #no longer supported as min requirements are 1.9.3
  - jruby-19mode
  - jruby-head
  - rbx
    #- ree #no longer supported as min requirements are 1.9.3
script: bundle exec rake
matrix:
  allow_failures:
    #not entirely sure what the error is with this, need to look in to it more, volunteers?
    - rvm: rbx 
    #known issues with interop on 2y, jBCrypt has not been updated in years :(
    - rvm: jruby-19mode
    - rvm: jruby-head
  fast_finish: true
