language: ruby
before_install:
  # jruby-head does not have bundler.
  - which bundle || gem install bundler
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.1
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx
  - ree
script: bundle exec rake
matrix:
  allow_failures:
    - rvm: rbx
    #considering new min requirements of 1.9.3 as many branches seem to have this a min
    - rvm: ree
    - rvm: 1.8.7
    - rvm: 1.9.2
    - rvm: jruby-18mode 
    #considering dropping jruby 1.9 as incompatible, and those case use bcrypt 3.x line
    - rvm: jruby-19mode
  fast_finish: true
